name: TrackerPro Cloud Runner
on:
  schedule:
    - cron: '0 * * * *' # يشتغل كل ساعة لضمان الاستمرارية
  workflow_dispatch: # زرار تشغيل يدوي

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Libs
        run: pip install firebase-admin selenium webdriver-manager
      - name: Start RealTime
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
        run: python "trck pro.py"
